# Generated by Django 3.2.7 on 2021-10-31 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', related_query_name='tweets_query', to='auth.user'),
            preserve_default=False,
        ),
    ]
