# Generated by Django 3.2.7 on 2021-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
