# Generated by Django 3.2.7 on 2021-11-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0002_tweet_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_id',
            new_name='user',
        ),
    ]
