# Generated by Django 3.2.9 on 2021-11-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0003_rename_user_id_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text_content',
            field=models.TextField(default='text tweet'),
            preserve_default=False,
        ),
    ]
